markdown: rdiscount
permalink: /:title/
url: lewki.github.io
baseurl: /
name: tianlu.me
author: cris tien
qq: 458910009
wechat: tianlu_me
email: ulnait@126.com	
github: lewki
duoshuo: cristo
pygments: true
safe: true
paginate: 20
about: " <p> *本博客clone自 - [webfrogs](https://github.com/webfrogs/webfrogs.github.com) 非常感谢这个简洁的模板* 


Humility comes before honor
