markdown: rdiscount
permalink: /:title/
url: lewki.github.io
baseurl: /
name: tianlu.me
author: criso
qq: 458910009
email: ulnait@126.com	
github: lewki
duoshuo: cristo
pygments: true
safe: true
paginate: 20
about: " <p> *本博客clone自 - [webfrogs](https://github.com/webfrogs/webfrogs.github.com) 非常感谢这个简洁的模板* </p> 
<p>爱好: 阅读，听音乐，爬山，追随心灵的自由。 </p>


|< ** Humility comes before honor ** >| 尊荣之前必得谦卑 |  
<p>name tianlu | nick_name cristo | username ulanit | project_name lewki </p>"
